ml_blueprint:
  data:
    source_path: ./data/playground-series-s4e12
    target_path: ./data
    split:
      train_size: 0.6
      val_size: 0.2
      test_size: 0.2
      random_state: 42
  training:
    target_column: Premium Amount
    drop_columns: ['Policy Start Date']
  model:
    random_state: 42
    xgb:
      n_estimators: 300
      learning_rate: 0.17
      max_depth: 7
      subsample: 0.3
      colsample_bytree: 0.7
      colsample_bylevel: 0.7
      reg_lambda: 1.0
      reg_alpha: 0.0
      objective: reg:squarederror
      booster: dart
      n_jobs: -1
      tree_method: auto
      verbosity: 0

